---
install_path: "{{ devtools_path }}/lint-config"
# Version of checkstyle to install
checkstyle_version: 8.37
# Version of detekt to install
detekt_version: v1.14.2

# Set the specific version of Node.js to install ("4.8.0", "6.11.0").
# use lts for latest Long Term Release
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "lts"

# NVM has a bash autocomplete functionality for when a user logs into a machine. Cool feature
# but only works when a human logs into said machine. More of a convienence method for this role
autocomplete: false

# NVM will automatically alias First Run version as default which is more than likely
# what people will use this for This will allow for installation/upgrade of multiple versions on an existing
# machine for the scenarios described in
# https://github.com/morgangraphics/ansible-role-nvm/pull/7#issuecomment-481423099
default: false

# The next 3 options only apply to wget and curl - If you don't know what you're doing
# you are fine to leave these alone.
#
# NVM Default directory
# NVM will, by default, install the .nvm directory in the home directory of the user e.g. /home/vagrant/.nvm
# You can override the installation directory by changing this variable e.g. /opt/nvm to put it into a
# global space (meaning not tied to a specific user account) if you wanted. This variable will respect
# Ansible substitution variables e.g. nvm_dir: "{{ansible_env.HOME}}/.nvm"
nvm_dir: ""

# AdHoc NVM Commands
nvm_commands: []

# Options are wget, curl, git
# Git :default dest: is the same as nvm_profile below.
nvm_install: "wget"

# The location of the SHELL profile that will source the nvm command from. There are two potential contexts to consider,
# globally, meaning everyone who logs in will have access to nvm (which may or may not what you really want)
# e.g /etc/bash.bashrc, /etc/profile, etc.
nvm_profile: "~/.bashrc"

# NVM source location - i.e. you host your own fork
nvm_source: ""

# Version of NVM to install
nvm_version: "0.35.2"

# Uninstall NVM
uninstall: false
