---
# Set up arcanist on the workstation
#
# We use the repos on github in order to control the location of the installation,
# and keep up to speed with the latest version.

- name: Ensure install path exists
  file:
    path: "{{ install_path }}"
    state: directory
    mode: 0755

- name: Ensure libphutil
  git:
    repo: https://github.com/phacility/libphutil.git
    dest: "{{ install_path }}/libphutil"

- name: Ensure arcanist
  git:
    repo: https://github.com/phacility/arcanist.git
    dest: "{{ install_path }}/arcanist"

- name: Ensure dev-tools-arcanist extensions
  git:
    repo: https://github.com/elhub/dev-tools-arcanist.git
    dest: "{{ install_path }}/extensions"

- name: Write arcconfig
  template:
    src: arcconfig.j2
    dest: "{{ install_path }}/config"
    mode: 0644

- name: Link /etc/arcconfig
  file:
    src: "{{ install_path }}/config"
    dest: /etc/arcconfig
    state: link
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Link arc
  file:
    src: "{{ install_path }}/arcanist/bin/arc"
    dest: /usr/local/bin/arc
    state: link
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Link phage
  file:
    src: "{{ install_path }}/arcanist/bin/phage"
    dest: /usr/local/bin/phage
    state: link
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set up arc-init
  template:
    src: arc-init.sh.j2
    dest: /usr/local/bin/arc-init
    mode: 0755
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure template path exists
  file:
    path: "{{ install_path }}/templates/repo"
    state: directory
    mode: 0755

- name: Set up repo-related templates
  template:
    src: "repo/{{ item }}.j2"
    dest: "{{ install_path }}/templates/repo/{{ item }}"
    mode: 0644
  loop:
    - ansible-lint-template
    - arcconfig-gradle-template
    - arcconfig-maven-template
    - arcconfig-none-template
    - arclint-template
    - CONTRIBUTING-template.md
    - gitattributes-template
    - gitignore-template
    - Makefile-template
    - README-template.md
    - yamllint-template
